/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TheShowRouteImport } from './routes/the-show'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ScoringRouteImport } from './routes/scoring'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlayRouteImport } from './routes/play'
import { Route as GameRulesRouteImport } from './routes/game-rules'
import { Route as FifaSpecialRouteImport } from './routes/fifa-special'
import { Route as FairPlayRouteImport } from './routes/fair-play'
import { Route as BlueprintRouteImport } from './routes/blueprint'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSecurityRouteImport } from './routes/_authenticated/security'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'

const TheShowRoute = TheShowRouteImport.update({
  id: '/the-show',
  path: '/the-show',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoringRoute = ScoringRouteImport.update({
  id: '/scoring',
  path: '/scoring',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRulesRoute = GameRulesRouteImport.update({
  id: '/game-rules',
  path: '/game-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const FifaSpecialRoute = FifaSpecialRouteImport.update({
  id: '/fifa-special',
  path: '/fifa-special',
  getParentRoute: () => rootRouteImport,
} as any)
const FairPlayRoute = FairPlayRouteImport.update({
  id: '/fair-play',
  path: '/fair-play',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintRoute = BlueprintRouteImport.update({
  id: '/blueprint',
  path: '/blueprint',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSecurityRoute = AuthenticatedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blueprint': typeof BlueprintRoute
  '/fair-play': typeof FairPlayRoute
  '/fifa-special': typeof FifaSpecialRoute
  '/game-rules': typeof GameRulesRoute
  '/play': typeof PlayRoute
  '/privacy': typeof PrivacyRoute
  '/rankings': typeof RankingsRoute
  '/rewards': typeof RewardsRoute
  '/scoring': typeof ScoringRoute
  '/terms': typeof TermsRoute
  '/the-show': typeof TheShowRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/security': typeof AuthenticatedSecurityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blueprint': typeof BlueprintRoute
  '/fair-play': typeof FairPlayRoute
  '/fifa-special': typeof FifaSpecialRoute
  '/game-rules': typeof GameRulesRoute
  '/play': typeof PlayRoute
  '/privacy': typeof PrivacyRoute
  '/rankings': typeof RankingsRoute
  '/rewards': typeof RewardsRoute
  '/scoring': typeof ScoringRoute
  '/terms': typeof TermsRoute
  '/the-show': typeof TheShowRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/security': typeof AuthenticatedSecurityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/blueprint': typeof BlueprintRoute
  '/fair-play': typeof FairPlayRoute
  '/fifa-special': typeof FifaSpecialRoute
  '/game-rules': typeof GameRulesRoute
  '/play': typeof PlayRoute
  '/privacy': typeof PrivacyRoute
  '/rankings': typeof RankingsRoute
  '/rewards': typeof RewardsRoute
  '/scoring': typeof ScoringRoute
  '/terms': typeof TermsRoute
  '/the-show': typeof TheShowRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/security': typeof AuthenticatedSecurityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/blueprint'
    | '/fair-play'
    | '/fifa-special'
    | '/game-rules'
    | '/play'
    | '/privacy'
    | '/rankings'
    | '/rewards'
    | '/scoring'
    | '/terms'
    | '/the-show'
    | '/dashboard'
    | '/onboarding'
    | '/profile'
    | '/security'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/blueprint'
    | '/fair-play'
    | '/fifa-special'
    | '/game-rules'
    | '/play'
    | '/privacy'
    | '/rankings'
    | '/rewards'
    | '/scoring'
    | '/terms'
    | '/the-show'
    | '/dashboard'
    | '/onboarding'
    | '/profile'
    | '/security'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/blueprint'
    | '/fair-play'
    | '/fifa-special'
    | '/game-rules'
    | '/play'
    | '/privacy'
    | '/rankings'
    | '/rewards'
    | '/scoring'
    | '/terms'
    | '/the-show'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/_authenticated/security'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlueprintRoute: typeof BlueprintRoute
  FairPlayRoute: typeof FairPlayRoute
  FifaSpecialRoute: typeof FifaSpecialRoute
  GameRulesRoute: typeof GameRulesRoute
  PlayRoute: typeof PlayRoute
  PrivacyRoute: typeof PrivacyRoute
  RankingsRoute: typeof RankingsRoute
  RewardsRoute: typeof RewardsRoute
  ScoringRoute: typeof ScoringRoute
  TermsRoute: typeof TermsRoute
  TheShowRoute: typeof TheShowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/the-show': {
      id: '/the-show'
      path: '/the-show'
      fullPath: '/the-show'
      preLoaderRoute: typeof TheShowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scoring': {
      id: '/scoring'
      path: '/scoring'
      fullPath: '/scoring'
      preLoaderRoute: typeof ScoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game-rules': {
      id: '/game-rules'
      path: '/game-rules'
      fullPath: '/game-rules'
      preLoaderRoute: typeof GameRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fifa-special': {
      id: '/fifa-special'
      path: '/fifa-special'
      fullPath: '/fifa-special'
      preLoaderRoute: typeof FifaSpecialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fair-play': {
      id: '/fair-play'
      path: '/fair-play'
      fullPath: '/fair-play'
      preLoaderRoute: typeof FairPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprint': {
      id: '/blueprint'
      path: '/blueprint'
      fullPath: '/blueprint'
      preLoaderRoute: typeof BlueprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/security': {
      id: '/_authenticated/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthenticatedSecurityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSecurityRoute: typeof AuthenticatedSecurityRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSecurityRoute: AuthenticatedSecurityRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BlueprintRoute: BlueprintRoute,
  FairPlayRoute: FairPlayRoute,
  FifaSpecialRoute: FifaSpecialRoute,
  GameRulesRoute: GameRulesRoute,
  PlayRoute: PlayRoute,
  PrivacyRoute: PrivacyRoute,
  RankingsRoute: RankingsRoute,
  RewardsRoute: RewardsRoute,
  ScoringRoute: ScoringRoute,
  TermsRoute: TermsRoute,
  TheShowRoute: TheShowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
